version: "3.3"
services:
  testui:
    container_name: testui
    build:
      context: .
    ports:
      - "7860:7860"
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
